---
collections:
  - name: community.general
    version: "*"  # Mantiene tu configuración actual para general

  - name: ansible.posix
    version: "*"  # Agregamos posix para soportar 'firewalld' en RedHat/CentOS